/**
 * Daily notes extractor (Felixcraft Layer-2 daily-notes parity).
 *
 * Builds `memory/daily/YYYY-MM-DD.md` for one calendar day in UTC, summarising:
 *   - Key Events             (timestamped run_events for that day)
 *   - Decisions Made         (workflow_changelog entries that day)
 *   - Facts Extracted        (workflow_feedback rows opened that day, dedup'd)
 *   - Active Long-Running    (runs with status='active' as of the day's end)
 *
 * Returns { dateIso, content } so the cron route can write it. Idempotent —
 * safe to re-run for the same day (the markdown overwrites cleanly).
 */

import { createServerClient } from '@/lib/supabase'

interface RunEventRow {
  run_id:     string
  kind:       string
  payload:    Record<string, unknown> | null
  created_at: string
}
interface ChangelogRow { agent_slug: string; summary: string | null; created_at: string }
interface FeedbackRow  { agent_slug: string; feedback: string;       created_at: string }
interface ActiveRunRow { id: string; phase: string; created_at: string; updated_at: string }

export interface DailyNote { dateIso: string; content: string; counts: Record<string, number> }

function dayBoundsUtc(dateIso: string): { startIso: string; endIso: string } {
  const d = new Date(dateIso + 'T00:00:00Z')
  const end = new Date(d.getTime() + 24 * 60 * 60 * 1000)
  return { startIso: d.toISOString(), endIso: end.toISOString() }
}

function fmtTime(iso: string): string {
  return new Date(iso).toISOString().slice(11, 16) + ' UTC'
}

function summariseEvent(ev: RunEventRow): string {
  const p = ev.payload ?? {}
  const agent = (p.agentSlug as string | undefined) ?? ''
  const status = (p.status as string | undefined) ?? ''
  const tail = [agent, status].filter(Boolean).join(' · ')
  return `${ev.kind}${tail ? ` (${tail})` : ''}`
}

export async function buildDailyNote(dateIso: string): Promise<DailyNote> {
  const { startIso, endIso } = dayBoundsUtc(dateIso)
  const counts = { events: 0, changelog: 0, feedback: 0, activeRuns: 0 }
  const lines = [`# ${dateIso}`, '']

  const db = createServerClient()
  if (!db) {
    lines.push('> Supabase not configured — daily extraction skipped.', '')
    return { dateIso, content: lines.join('\n'), counts }
  }

  const events = await safeSelect<RunEventRow>(
    db, 'run_events', 'run_id,kind,payload,created_at',
    [['gte', 'created_at', startIso], ['lt', 'created_at', endIso]],
    'created_at', false,
  )
  counts.events = events.length

  const changelog = await safeSelect<ChangelogRow>(
    db, 'workflow_changelog', 'agent_slug,summary,created_at',
    [['gte', 'created_at', startIso], ['lt', 'created_at', endIso]],
    'created_at', false,
  )
  counts.changelog = changelog.length

  const feedback = await safeSelect<FeedbackRow>(
    db, 'workflow_feedback', 'agent_slug,feedback,created_at',
    [['gte', 'created_at', startIso], ['lt', 'created_at', endIso]],
    'created_at', false,
  )
  counts.feedback = feedback.length

  const active = await safeSelect<ActiveRunRow>(
    db, 'runs', 'id,phase,created_at,updated_at',
    [['eq', 'status', 'active'], ['lt', 'created_at', endIso]],
    'updated_at', false,
  )
  counts.activeRuns = active.length

  lines.push('## Key Events')
  if (events.length === 0) lines.push('- (no run events)')
  for (const ev of events.slice(0, 50)) {
    lines.push(`- ${fmtTime(ev.created_at)} — \`${ev.run_id.slice(0, 8)}\` ${summariseEvent(ev)}`)
  }
  if (events.length > 50) lines.push(`- …and ${events.length - 50} more`)
  lines.push('')

  lines.push('## Decisions Made')
  if (changelog.length === 0) lines.push('- (no agent spec changes today)')
  for (const ch of changelog.slice(0, 30)) {
    lines.push(`- ${ch.agent_slug}: ${ch.summary ?? '(no summary)'}`)
  }
  lines.push('')

  lines.push('## Facts Extracted')
  if (feedback.length === 0) lines.push('- (no workflow feedback rows today)')
  const seen = new Set<string>()
  for (const fb of feedback) {
    const key = `${fb.agent_slug}::${fb.feedback}`
    if (seen.has(key)) continue
    seen.add(key)
    lines.push(`- ${fb.agent_slug} → ${fb.feedback.slice(0, 200)}`)
  }
  lines.push('')

  lines.push('## Active Long-Running Processes')
  if (active.length === 0) lines.push('- (none)')
  for (const r of active.slice(0, 30)) {
    lines.push(`- run \`${r.id.slice(0, 8)}\` · phase=${r.phase} · since ${r.created_at.slice(0, 10)}`)
  }
  lines.push('')
  lines.push('---', `_generated by lib/runs/daily-extractor.ts at ${new Date().toISOString()}_`)

  return { dateIso, content: lines.join('\n'), counts }
}

type Filter = ['eq' | 'gte' | 'lt', string, string]

async function safeSelect<T>(
  db: unknown,
  table: string,
  cols: string,
  filters: Filter[],
  orderBy: string,
  ascending: boolean,
): Promise<T[]> {
  try {
    let q = (db as { from: (t: string) => unknown }).from(table) as unknown as {
      select: (c: string) => unknown
    }
    let chain = q.select(cols) as unknown as Record<string, (...a: unknown[]) => unknown> & { order: (c: string, o: { ascending: boolean }) => Promise<{ data: T[] | null; error: unknown }> }
    for (const [op, col, val] of filters) {
      const fn = chain[op] as (c: string, v: string) => unknown
      chain = fn.call(chain, col, val) as typeof chain
    }
    const { data } = await chain.order(orderBy, { ascending })
    return data ?? []
  } catch {
    return []
  }
}
