import type {
  RevenueDataPoint,
  AgentRow,
  KanbanColumn,
  KpiCard,
} from './types'

// ── Revenue chart (12 months) ─────────────────────────────────────────────────
export const REVENUE_DATA: RevenueDataPoint[] = [
  { month: 'Jan', revenue: 0, cost: 1200 },
  { month: 'Feb', revenue: 800, cost: 1350 },
  { month: 'Mar', revenue: 2400, cost: 1500 },
  { month: 'Apr', revenue: 4100, cost: 1800 },
  { month: 'May', revenue: 6200, cost: 2100 },
  { month: 'Jun', revenue: 9500, cost: 2400 },
  { month: 'Jul', revenue: 11200, cost: 2700 },
  { month: 'Aug', revenue: 14800, cost: 3100 },
  { month: 'Sep', revenue: 17300, cost: 3400 },
  { month: 'Oct', revenue: 21000, cost: 3800 },
  { month: 'Nov', revenue: 25500, cost: 4200 },
  { month: 'Dec', revenue: 31200, cost: 4600 },
]

// ── KPI cards ─────────────────────────────────────────────────────────────────
export const KPI_DATA: KpiCard[] = [
  { label: 'Total Revenue',   value: '$31,200', delta: 22.4, color: 'green',   description: 'Sum of confirmed payments / sales attributed to Nexus-driven outputs in the selected window.' },
  { label: 'Total Cost',      value: '$4,600',  delta: 9.5,  color: 'red',     description: 'AI inference + third-party APIs + infra spend in the window.' },
  { label: 'Net Profit',      value: '$26,600', delta: 24.1, color: 'purple',  description: 'Total Revenue minus Total Cost. Negative means the platform is a net cost centre this window.' },
  { label: 'Active Agents',   value: '7',       delta: 2,    color: 'default', description: 'Distinct managed agents that ran at least one task in the window.' },
  { label: 'Tokens Used',     value: '4.2M',    delta: 18.3, color: 'default', description: 'Combined input + output tokens across every LLM call in the window. ~$3 per million on Sonnet, ~$15 per million on Opus.' },
  { label: 'Tasks Completed', value: '143',     delta: 31,   color: 'default', description: 'Kanban cards moved to the Completed column in the window.' },
]

// ── Agent rows ────────────────────────────────────────────────────────────────
export const AGENT_ROWS: AgentRow[] = [
  {
    id: 'a1',
    name: 'ResearchBot-Alpha',
    status: 'active',
    tasksCompleted: 38,
    tokensUsed: 920000,
    costUsd: 13.8,
    lastActive: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: 'a2',
    name: 'ContentWriter-Beta',
    status: 'active',
    tasksCompleted: 27,
    tokensUsed: 1100000,
    costUsd: 16.5,
    lastActive: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'a3',
    name: 'MarketAnalyst-Gamma',
    status: 'idle',
    tasksCompleted: 19,
    tokensUsed: 540000,
    costUsd: 8.1,
    lastActive: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'a4',
    name: 'DevOps-Delta',
    status: 'active',
    tokensUsed: 780000,
    tasksCompleted: 31,
    costUsd: 11.7,
    lastActive: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
  },
  {
    id: 'a5',
    name: 'SEO-Epsilon',
    status: 'error',
    tasksCompleted: 12,
    tokensUsed: 310000,
    costUsd: 4.65,
    lastActive: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'a6',
    name: 'SalesOutreach-Zeta',
    status: 'active',
    tasksCompleted: 16,
    tokensUsed: 550000,
    costUsd: 8.25,
    lastActive: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
]

// ── Kanban columns ────────────────────────────────────────────────────────────
// NOTE: k_m1 / k_m2 are manual owner tasks; automated tasks depend_on them so
// the board can demo priority sorting without a real Supabase hit.
export const INITIAL_COLUMNS: KanbanColumn[] = [
  {
    id: 'backlog',
    label: 'Backlog',
    cards: [
      {
        id: 'k_m1',
        title: 'Approve brand voice guidelines',
        description: 'Owner review required before any content workflows can run.',
        columnId: 'backlog',
        assignee: 'You',
        priority: 'high',
        taskType: 'manual',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
      },
      {
        id: 'k1',
        title: 'Competitor analysis report',
        description: 'Deep-dive into top 5 competitors — pricing, positioning, weaknesses.',
        columnId: 'backlog',
        assignee: 'MarketAnalyst-Gamma',
        priority: 'medium',
        taskType: 'automated',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      },
      {
        id: 'k2',
        title: 'Brand identity guidelines',
        description: 'Logo variants, color palette, typography system, usage rules.',
        columnId: 'backlog',
        assignee: 'ContentWriter-Beta',
        priority: 'low',
        taskType: 'automated',
        dependsOn: ['k_m1'],
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
      },
    ],
  },
  {
    id: 'in-progress',
    label: 'In Progress',
    cards: [
      {
        id: 'k_m2',
        title: 'Provide Stripe API keys',
        description: 'Paste live + test keys into the Tools page so billing agents can go live.',
        columnId: 'in-progress',
        assignee: 'You',
        priority: 'high',
        taskType: 'manual',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
      },
      {
        id: 'k3',
        title: 'Landing page copy & SEO',
        description: 'Write all landing page sections optimised for target keywords.',
        columnId: 'in-progress',
        assignee: 'SEO-Epsilon',
        priority: 'high',
        taskType: 'automated',
        dependsOn: ['k_m1'],
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      },
      {
        id: 'k4',
        title: 'Infrastructure setup (Vercel + Supabase)',
        description: 'Configure prod environment, env vars via Doppler, CI/CD pipeline.',
        columnId: 'in-progress',
        assignee: 'DevOps-Delta',
        priority: 'high',
        taskType: 'automated',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      },
      {
        id: 'k5',
        title: 'Email outreach sequence (cold)',
        description: '5-step drip campaign targeting early adopters.',
        columnId: 'in-progress',
        assignee: 'SalesOutreach-Zeta',
        priority: 'medium',
        taskType: 'automated',
        dependsOn: ['k_m1'],
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        id: 'k_billing',
        title: 'Enable Stripe revenue sync',
        description: 'Wire Stripe webhook → Supabase → dashboard KPIs.',
        columnId: 'in-progress',
        assignee: 'DevOps-Delta',
        priority: 'medium',
        taskType: 'automated',
        dependsOn: ['k_m2'],
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
      },
    ],
  },
  {
    id: 'review',
    label: 'Review',
    cards: [
      {
        id: 'k6',
        title: 'Market research PDF',
        description: '42-page market sizing and opportunity analysis.',
        columnId: 'review',
        assignee: 'ResearchBot-Alpha',
        priority: 'high',
        taskType: 'automated',
        assetUrl: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/pdf-sample.pdf',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
      },
      {
        id: 'k7',
        title: 'Social media content calendar',
        description: '30 days of posts across LinkedIn, X, and Instagram.',
        columnId: 'review',
        assignee: 'ContentWriter-Beta',
        priority: 'medium',
        taskType: 'automated',
        assetUrl: 'https://docs.google.com/spreadsheets/d/example',
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      },
    ],
  },
  {
    id: 'completed',
    label: 'Completed',
    cards: [
      {
        id: 'k8',
        title: 'Business model canvas',
        description: 'Full BMC covering value props, channels, revenue streams.',
        columnId: 'completed',
        assignee: 'ResearchBot-Alpha',
        priority: 'high',
        taskType: 'automated',
        assetUrl: 'https://miro.com/app/board/example',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
      },
    ],
  },
]
