/**
 * scripts/local-os-business.ts
 *
 * Manage per-business Claude-gateway containers on the Mac local-OS stack
 * (OrbStack + docker-compose), replacing Coolify-on-KVM4 hosting for the
 * per-business tier. See services/local-os/businesses/README.md + ADR 011.
 *
 * Usage (host-side, on the Mac — the app container has no docker socket):
 *
 *   npm run business:local -- add <slug> [--niche=<profile>] [--packages="a b"]
 *   npm run business:local -- up      <slug>
 *   npm run business:local -- down    <slug>
 *   npm run business:local -- rebuild <slug>
 *   npm run business:local -- list
 *   npm run business:local -- sync                 # regen compose from *.env
 *   npm run business:local -- secret  <slug>       # print gatewayUrl + bearer
 *
 * `add` resolves the business's MCP manifest, builds the arm64 image locally,
 * generates a gitignored <slug>.env (DOPPLER_TOKEN + per-business bearer/slug/
 * profile), regenerates docker-compose.yaml, and brings the container up on the
 * shared `coolify` network at internal DNS nexus-business-<slug>:3000.
 *
 * What it deliberately does NOT do (operator-gated, irreversible/prod):
 *   - Write the business:<slug> gateway secret to prod user_secrets (use the
 *     output of `secret <slug>` + the normal approved secret path).
 *   - Delete the old Coolify nexus-business-<slug> app.
 *   - Publish any public DNS / Cloudflare ingress (internal DNS suffices).
 */

import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { randomBytes } from 'node:crypto'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { BUSINESS_SEEDS } from '../lib/business/seeds'
import { resolveManifest } from '../lib/businesses/mcp-manifest'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, '..')
const BUSINESSES_DIR = path.join(REPO_ROOT, 'services/local-os/businesses')
const LOCAL_OS_ENV = path.join(REPO_ROOT, 'services/local-os/.env')
const DOCKERFILE = path.join(REPO_ROOT, 'services/claude-gateway/Dockerfile.business')
const BUILD_CONTEXT = path.join(REPO_ROOT, 'services/claude-gateway')
const COMPOSE_FILE = path.join(BUSINESSES_DIR, 'docker-compose.yaml')
const COMPOSE_PROJECT = 'local-os-businesses'
const NETWORK = 'coolify'

const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,38}[a-z0-9]$/

function fail(msg: string): never {
  console.error(`✗ ${msg}`)
  process.exit(1)
}

function run(cmd: string, args: string[], opts: { quiet?: boolean } = {}): number {
  if (!opts.quiet) console.log(`  $ ${cmd} ${args.join(' ')}`)
  const r = spawnSync(cmd, args, { stdio: 'inherit' })
  return r.status ?? 1
}

function readDopplerToken(): string {
  if (!fs.existsSync(LOCAL_OS_ENV)) {
    fail(`${LOCAL_OS_ENV} not found — set up the local-OS stack first (services/local-os/README.md).`)
  }
  const txt = fs.readFileSync(LOCAL_OS_ENV, 'utf8')
  const m = txt.match(/^\s*DOPPLER_TOKEN\s*=\s*(.+?)\s*$/m)
  if (!m) fail(`DOPPLER_TOKEN not found in ${LOCAL_OS_ENV}`)
  return m[1].replace(/^["']|["']$/g, '')
}

function envFilePath(slug: string): string {
  return path.join(BUSINESSES_DIR, `${slug}.env`)
}

function listSlugs(): string[] {
  if (!fs.existsSync(BUSINESSES_DIR)) return []
  return fs
    .readdirSync(BUSINESSES_DIR)
    .filter((f) => f.endsWith('.env'))
    .map((f) => f.slice(0, -'.env'.length))
    .sort()
}

/** Parse a slug's existing env file into a key→value map. */
function readEnvFile(slug: string): Record<string, string> {
  const p = envFilePath(slug)
  if (!fs.existsSync(p)) fail(`${slug} not defined — run \`add ${slug}\` first.`)
  const out: Record<string, string> = {}
  for (const line of fs.readFileSync(p, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/)
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, '')
  }
  return out
}

function resolveNiche(slug: string, override?: string): string {
  if (override) return override
  const seed = BUSINESS_SEEDS.find((b) => b.slug === slug)
  if (seed) return seed.niche
  fail(`No seed found for "${slug}" — pass --niche=<profile> (e.g. --niche=saas).`)
}

/** Write (or refresh) the gitignored <slug>.env. Reuses an existing bearer. */
function writeEnvFile(slug: string, profile: string): { bearer: string; created: boolean } {
  const p = envFilePath(slug)
  const existing = fs.existsSync(p) ? readEnvFile(slug) : null
  const bearer = existing?.CLAUDE_GATEWAY_BEARER || randomBytes(32).toString('hex')
  const token = readDopplerToken()
  const body = [
    `# Per-business container env for ${slug} — GITIGNORED, host-local only.`,
    `# Generated by scripts/local-os-business.ts. DOPPLER_TOKEN supplies all`,
    `# global secrets at boot via the image's \`doppler run --\` entrypoint;`,
    `# only the per-business overrides below are not global Doppler secrets.`,
    `DOPPLER_TOKEN=${token}`,
    `NEXUS_BUSINESS_SLUG=${slug}`,
    `CLAUDE_GATEWAY_BEARER=${bearer}`,
    `MCP_PROFILE=${profile}`,
    '',
  ].join('\n')
  fs.writeFileSync(p, body, { mode: 0o600 })
  return { bearer, created: !existing }
}

/** Regenerate docker-compose.yaml to cover every <slug>.env present. */
function regenCompose(): string[] {
  const slugs = listSlugs()
  const services: string[] = []
  const volumes: string[] = []
  for (const slug of slugs) {
    const svc = `nexus-business-${slug}`
    const vClaude = `business_${slug.replace(/-/g, '_')}_claude`
    const vRepo = `business_${slug.replace(/-/g, '_')}_repo`
    services.push(
      [
        `  ${svc}:`,
        `    image: nexus-business:${slug}`,
        `    pull_policy: never`,
        `    env_file:`,
        `      - ./${slug}.env`,
        `    restart: unless-stopped`,
        `    networks:`,
        `      ${NETWORK}:`,
        `        aliases:`,
        `          - ${svc}`,
        `    volumes:`,
        `      - ${vClaude}:/root/.claude`,
        `      - ${vRepo}:/repo`,
        `    healthcheck:`,
        `      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/health || exit 1"]`,
        `      interval: 30s`,
        `      timeout: 5s`,
        `      retries: 3`,
        // First boot clones the (large) Nexus repo + builds ~7 MCP wrappers
        // before the server listens — generous warmup so it doesn't flap.
        `      start_period: 360s`,
      ].join('\n'),
    )
    volumes.push(`  ${vClaude}:`, `  ${vRepo}:`)
  }
  const header = [
    '# GENERATED by scripts/local-os-business.ts — do not edit by hand.',
    '# Regenerate with: npm run business:local -- sync',
    '# One service per services/local-os/businesses/<slug>.env. Each joins the',
    '# external `coolify` network (shared with the main local-OS stack) at alias',
    '# nexus-business-<slug>, so nexus-app reaches it internally at',
    '# http://nexus-business-<slug>:3000 — no public tunnel/DNS required.',
    '',
  ].join('\n')
  const doc =
    header +
    (services.length ? 'services:\n' + services.join('\n\n') + '\n\n' : 'services: {}\n\n') +
    `networks:\n  ${NETWORK}:\n    external: true\n` +
    (volumes.length ? '\nvolumes:\n' + volumes.join('\n') + '\n' : '')
  fs.writeFileSync(COMPOSE_FILE, doc)
  return slugs
}

function dockerBuild(slug: string, mcpPackages: string): void {
  console.log(`▶ Building nexus-business:${slug} (arm64) …`)
  const code = run('docker', [
    'build',
    '--build-arg', `BUSINESS_SLUG=${slug}`,
    '--build-arg', `MCP_PACKAGES=${mcpPackages}`,
    '-f', DOCKERFILE,
    '-t', `nexus-business:${slug}`,
    BUILD_CONTEXT,
  ])
  if (code !== 0) fail(`docker build failed for ${slug}`)
}

function composeUp(slug?: string): void {
  regenCompose()
  const args = ['compose', '-p', COMPOSE_PROJECT, '-f', COMPOSE_FILE, 'up', '-d']
  if (slug) args.push(`nexus-business-${slug}`)
  if (run('docker', args) !== 0) fail('docker compose up failed')
}

function composeDown(slug: string): void {
  regenCompose()
  const code = run('docker', [
    'compose', '-p', COMPOSE_PROJECT, '-f', COMPOSE_FILE, 'stop', `nexus-business-${slug}`,
  ])
  if (code !== 0) fail('docker compose stop failed')
}

function cmdAdd(slug: string, opts: { niche?: string; packages?: string }): void {
  if (!SLUG_RE.test(slug)) fail(`Invalid slug "${slug}" (lowercase letters, digits, hyphens).`)
  const niche = resolveNiche(slug, opts.niche)
  const manifest = resolveManifest({ niche })
  const mcpPackages = opts.packages ?? '' // pilot default = none (foundational resolve at runtime)
  console.log(`Business: ${slug}`)
  console.log(`  niche:    ${niche}`)
  console.log(`  profile:  ${manifest.profile}`)
  console.log(`  MCPs:     ${manifest.mcpIds.join(', ')}`)
  console.log(`  packages: ${mcpPackages || '(none — mcp_override=none; runtime-resolved)'}`)
  console.log('')

  dockerBuild(slug, mcpPackages)
  const { created } = writeEnvFile(slug, manifest.profile)
  console.log(`  ${created ? 'Generated' : 'Reused'} ${slug}.env (bearer ${created ? 'new' : 'preserved'}).`)
  composeUp(slug)

  console.log('')
  console.log(`✓ ${slug} is up at internal DNS http://nexus-business-${slug}:3000`)
  console.log('  Next steps:')
  console.log(`    1. Smoke-test:  npm run business:local -- list`)
  console.log(`    2. GATED prod cutover — store the dispatch secret:`)
  console.log(`         npm run business:local -- secret ${slug}`)
  console.log(`       then write business:${slug} gatewayUrl + bearerToken to user_secrets (approved).`)
}

function cmdList(): void {
  const slugs = listSlugs()
  if (!slugs.length) {
    console.log('No per-business containers defined. Add one: npm run business:local -- add <slug>')
    return
  }
  regenCompose()
  console.log(`Defined businesses (${slugs.length}): ${slugs.join(', ')}\n`)
  run('docker', ['compose', '-p', COMPOSE_PROJECT, '-f', COMPOSE_FILE, 'ps'], { quiet: true })
}

function cmdSecret(slug: string): void {
  const env = readEnvFile(slug)
  const bearer = env.CLAUDE_GATEWAY_BEARER
  if (!bearer) fail(`No CLAUDE_GATEWAY_BEARER in ${slug}.env`)
  console.log(`# Dispatch routing secret for business:${slug}`)
  console.log(`# Store in user_secrets(kind=business:${slug}) — GATED prod write.`)
  console.log(`gatewayUrl=http://nexus-business-${slug}:3000`)
  console.log(`bearerToken=${bearer}`)
}

function main(): void {
  const [sub, ...rest] = process.argv.slice(2)
  const positional: string[] = []
  const flags: Record<string, string> = {}
  for (const a of rest) {
    const m = a.match(/^--([^=]+)=(.*)$/)
    if (m) flags[m[1]] = m[2]
    else positional.push(a)
  }
  const slug = positional[0]

  switch (sub) {
    case 'add':
      if (!slug) fail('Usage: add <slug> [--niche=<profile>] [--packages="a b"]')
      cmdAdd(slug, { niche: flags.niche, packages: flags.packages })
      break
    case 'up':
      if (!slug) fail('Usage: up <slug>')
      composeUp(slug)
      console.log(`✓ ${slug} up.`)
      break
    case 'down':
      if (!slug) fail('Usage: down <slug>')
      composeDown(slug)
      console.log(`✓ ${slug} stopped.`)
      break
    case 'rebuild': {
      if (!slug) fail('Usage: rebuild <slug>')
      const niche = resolveNiche(slug, flags.niche)
      const manifest = resolveManifest({ niche })
      dockerBuild(slug, flags.packages ?? '')
      writeEnvFile(slug, manifest.profile)
      composeUp(slug)
      console.log(`✓ ${slug} rebuilt + recreated.`)
      break
    }
    case 'sync': {
      const slugs = regenCompose()
      console.log(`✓ Regenerated ${COMPOSE_FILE} (${slugs.length} business(es)).`)
      break
    }
    case 'list':
      cmdList()
      break
    case 'secret':
      if (!slug) fail('Usage: secret <slug>')
      cmdSecret(slug)
      break
    default:
      console.error('Usage: local-os-business.ts <add|up|down|rebuild|sync|list|secret> [slug] [flags]')
      process.exit(1)
  }
}

main()
